In [2]:
import pandas as pd

df = pd.read_csv(r"C:\Users\HP\OneDrive\Desktop\All Project\amazon_payments.csv", low_memory = False)
print("Read_the_file")

Read_the_file

In [3]:
df.columns

Index(['txn_id', 'customer_id', 'txn_date', 'payment_method', 'status',
       'amount', 'city', 'merchant_category', 'coupon_used', 'device', 'bank',
       'processing_time_sec'],
      dtype='object')

In [4]:
df.head()

,txn_id,customer_id,txn_date,payment_method,status,amount,city,merchant_category,coupon_used,device,bank,processing_time_sec
0,T002,C002,01-01-2025,CARD,FAILED,1299,Bangalore,Electronics,NO,iOS,ICICI,35
1,T003,C003,02-01-2025,NETBANKING,SUCCESS,799,Chennai,Fashion,YES,Android,SBI,20
2,T004,C001,03-01-2025,COD,SUCCESS,999,Hyderabad,Electronics,NO,Android,HDFC,10
3,T005,C004,03-01-2025,UPI,PENDING,299,Pune,Grocery,NO,Android,AXIS,18
4,T006,C005,04-01-2025,CARD,SUCCESS,1999,Mumbai,Electronics,YES,iOS,HDFC,25

In [4]:
df['txn_date'] = pd.to_datetime(df["txn_date"], format="%d-%m-%Y")
df.head()

,txn_id,customer_id,txn_date,payment_method,status,amount,city,merchant_category,coupon_used,device,bank,processing_time_sec
0,T002,C002,2025-01-01,CARD,FAILED,1299,Bangalore,Electronics,NO,iOS,ICICI,35
1,T003,C003,2025-01-02,NETBANKING,SUCCESS,799,Chennai,Fashion,YES,Android,SBI,20
2,T004,C001,2025-01-03,COD,SUCCESS,999,Hyderabad,Electronics,NO,Android,HDFC,10
3,T005,C004,2025-01-03,UPI,PENDING,299,Pune,Grocery,NO,Android,AXIS,18
4,T006,C005,2025-01-04,CARD,SUCCESS,1999,Mumbai,Electronics,YES,iOS,HDFC,25

In [7]:
# 3.1 DataFrame Basics + Exploration

# 1. Print df.shape, df.columns, df.dtypes

df.shape #(rows,column)
df.columns #(column names)
df.dtypes #(data_type of each column)

txn_id                 object
customer_id            object
txn_date               object
payment_method         object
status                 object
amount                  int64
city                   object
merchant_category      object
coupon_used            object
device                 object
bank                   object
processing_time_sec     int64
dtype: object

In [20]:
# 2. Show df.head() and df.tail()

df.head()

,txn_id,customer_id,txn_date,payment_method,status,amount,city,merchant_category,coupon_used,device,bank,processing_time_sec
0,T002,C002,01-01-2025,CARD,FAILED,1299,Bangalore,Electronics,NO,iOS,ICICI,35
1,T003,C003,02-01-2025,NETBANKING,SUCCESS,799,Chennai,Fashion,YES,Android,SBI,20
2,T004,C001,03-01-2025,COD,SUCCESS,999,Hyderabad,Electronics,NO,Android,HDFC,10
3,T005,C004,03-01-2025,UPI,PENDING,299,Pune,Grocery,NO,Android,AXIS,18
4,T006,C005,04-01-2025,CARD,SUCCESS,1999,Mumbai,Electronics,YES,iOS,HDFC,25

In [21]:
df.tail()

,txn_id,customer_id,txn_date,payment_method,status,amount,city,merchant_category,coupon_used,device,bank,processing_time_sec
14,T016,C011,10-01-2025,CARD,SUCCESS,2200,Bangalore,Electronics,YES,iOS,HDFC,27
15,T017,C012,11-01-2025,UPI,SUCCESS,99,Chennai,Grocery,NO,Android,SBI,6
16,T018,C005,12-01-2025,UPI,PENDING,750,Mumbai,Travel,YES,Android,HDFC,19
17,T019,C007,12-01-2025,CARD,SUCCESS,1599,Hyderabad,Fashion,NO,iOS,ICICI,21
18,T020,C002,13-01-2025,UPI,SUCCESS,450,Bangalore,Travel,YES,Android,ICICI,10

In [22]:
# 3. Use df.describe() for numeric summary

df.describe()

            amount  processing_time_sec
count    19.000000            19.000000
mean    883.684211            19.421053
std     639.455155             9.605067
min      99.000000             6.000000
25%     399.500000            10.500000
50%     750.000000            19.000000
75%    1249.500000            26.000000
max    2200.000000            40.000000

In [23]:
# 4. Find missing values per column using df.isnull().sum()

df.isnull().sum()

txn_id                 0
customer_id            0
txn_date               0
payment_method         0
status                 0
amount                 0
city                   0
merchant_category      0
coupon_used            0
device                 0
bank                   0
processing_time_sec    0
dtype: int64

In [24]:
# 3.2 Filtering + Selection

# 1. Filter all SUCCESS transactions

f_df = df[df['status']=="SUCCESS"]
f_df.head()
f_df.shape

(14, 12)

In [25]:
# 2. Filter transactions where amount > 1000

f_df = f_df[f_df['amount']> 1000]
f_df.shape

(4, 12)

In [26]:
# 3. Filter Bangalore + UPI transactions

fc_df = df[(df["city"]=="Bangalore") & (df["payment_method"] == "UPI")]
fc_df
# df[(df["city"] == "Bangalore") & (df["payment_method"] == "UPI")]

,txn_id,customer_id,txn_date,payment_method,status,amount,city,merchant_category,coupon_used,device,bank,processing_time_sec
5,T007,C002,04-01-2025,UPI,SUCCESS,150,Bangalore,Grocery,NO,Android,ICICI,9
9,T011,C008,07-01-2025,UPI,SUCCESS,349,Bangalore,Grocery,YES,Android,AXIS,11
18,T020,C002,13-01-2025,UPI,SUCCESS,450,Bangalore,Travel,YES,Android,ICICI,10

In [27]:
# 4. Filter all rows where status != SUCCESS

not_success = df[df['status'] != "SUCCESS"]
not_success

,txn_id,customer_id,txn_date,payment_method,status,amount,city,merchant_category,coupon_used,device,bank,processing_time_sec
0,T002,C002,01-01-2025,CARD,FAILED,1299,Bangalore,Electronics,NO,iOS,ICICI,35
3,T005,C004,03-01-2025,UPI,PENDING,299,Pune,Grocery,NO,Android,AXIS,18
7,T009,C003,06-01-2025,UPI,FAILED,1200,Chennai,Electronics,NO,iOS,SBI,40
11,T013,C009,08-01-2025,CARD,FAILED,500,Delhi,Grocery,NO,iOS,ICICI,28
16,T018,C005,12-01-2025,UPI,PENDING,750,Mumbai,Travel,YES,Android,HDFC,19

In [28]:
# 3.3 Sorting

# 1. Sort by amount descending

sdf = df.sort_values(by = "amount",ascending= False) 
sdf

,txn_id,customer_id,txn_date,payment_method,status,amount,city,merchant_category,coupon_used,device,bank,processing_time_sec
14,T016,C011,10-01-2025,CARD,SUCCESS,2200,Bangalore,Electronics,YES,iOS,HDFC,27
4,T006,C005,04-01-2025,CARD,SUCCESS,1999,Mumbai,Electronics,YES,iOS,HDFC,25
13,T015,C006,10-01-2025,NETBANKING,SUCCESS,1800,Delhi,Electronics,NO,Android,KOTAK,30
17,T019,C007,12-01-2025,CARD,SUCCESS,1599,Hyderabad,Fashion,NO,iOS,ICICI,21
0,T002,C002,01-01-2025,CARD,FAILED,1299,Bangalore,Electronics,NO,iOS,ICICI,35
7,T009,C003,06-01-2025,UPI,FAILED,1200,Chennai,Electronics,NO,iOS,SBI,40
2,T004,C001,03-01-2025,COD,SUCCESS,999,Hyderabad,Electronics,NO,Android,HDFC,10
10,T012,C004,08-01-2025,COD,SUCCESS,899,Pune,Fashion,NO,Android,AXIS,14
1,T003,C003,02-01-2025,NETBANKING,SUCCESS,799,Chennai,Fashion,YES,Android,SBI,20
16,T018,C005,12-01-2025,UPI,PENDING,750,Mumbai,Travel,YES,Android,HDFC,19
8,T010,C007,06-01-2025,NETBANKING,SUCCESS,650,Hyderabad,Travel,NO,Android,HDFC,22
11,T013,C009,08-01-2025,CARD,FAILED,500,Delhi,Grocery,NO,iOS,ICICI,28
6,T008,C006,05-01-2025,CARD,SUCCESS,499,Delhi,Fashion,YES,Android,KOTAK,16
18,T020,C002,13-01-2025,UPI,SUCCESS,450,Bangalore,Travel,YES,Android,ICICI,10
9,T011,C008,07-01-2025,UPI,SUCCESS,349,Bangalore,Grocery,YES,Android,AXIS,11
3,T005,C004,03-01-2025,UPI,PENDING,299,Pune,Grocery,NO,Android,AXIS,18
12,T014,C010,09-01-2025,UPI,SUCCESS,250,Mumbai,Grocery,YES,Android,HDFC,8
5,T007,C002,04-01-2025,UPI,SUCCESS,150,Bangalore,Grocery,NO,Android,ICICI,9
15,T017,C012,11-01-2025,UPI,SUCCESS,99,Chennai,Grocery,NO,Android,SBI,6

In [29]:
# 2. Sort by txn_date ascending and amount descending

sdf = df.sort_values(by =["txn_date","amount"] , ascending = [True,False] )
sdf

,txn_id,customer_id,txn_date,payment_method,status,amount,city,merchant_category,coupon_used,device,bank,processing_time_sec
0,T002,C002,01-01-2025,CARD,FAILED,1299,Bangalore,Electronics,NO,iOS,ICICI,35
1,T003,C003,02-01-2025,NETBANKING,SUCCESS,799,Chennai,Fashion,YES,Android,SBI,20
2,T004,C001,03-01-2025,COD,SUCCESS,999,Hyderabad,Electronics,NO,Android,HDFC,10
3,T005,C004,03-01-2025,UPI,PENDING,299,Pune,Grocery,NO,Android,AXIS,18
4,T006,C005,04-01-2025,CARD,SUCCESS,1999,Mumbai,Electronics,YES,iOS,HDFC,25
5,T007,C002,04-01-2025,UPI,SUCCESS,150,Bangalore,Grocery,NO,Android,ICICI,9
6,T008,C006,05-01-2025,CARD,SUCCESS,499,Delhi,Fashion,YES,Android,KOTAK,16
7,T009,C003,06-01-2025,UPI,FAILED,1200,Chennai,Electronics,NO,iOS,SBI,40
8,T010,C007,06-01-2025,NETBANKING,SUCCESS,650,Hyderabad,Travel,NO,Android,HDFC,22
9,T011,C008,07-01-2025,UPI,SUCCESS,349,Bangalore,Grocery,YES,Android,AXIS,11
10,T012,C004,08-01-2025,COD,SUCCESS,899,Pune,Fashion,NO,Android,AXIS,14
11,T013,C009,08-01-2025,CARD,FAILED,500,Delhi,Grocery,NO,iOS,ICICI,28
12,T014,C010,09-01-2025,UPI,SUCCESS,250,Mumbai,Grocery,YES,Android,HDFC,8
14,T016,C011,10-01-2025,CARD,SUCCESS,2200,Bangalore,Electronics,YES,iOS,HDFC,27
13,T015,C006,10-01-2025,NETBANKING,SUCCESS,1800,Delhi,Electronics,NO,Android,KOTAK,30
15,T017,C012,11-01-2025,UPI,SUCCESS,99,Chennai,Grocery,NO,Android,SBI,6
17,T019,C007,12-01-2025,CARD,SUCCESS,1599,Hyderabad,Fashion,NO,iOS,ICICI,21
16,T018,C005,12-01-2025,UPI,PENDING,750,Mumbai,Travel,YES,Android,HDFC,19
18,T020,C002,13-01-2025,UPI,SUCCESS,450,Bangalore,Travel,YES,Android,ICICI,10

In [30]:
# 3.4 Aggregation + GroupBy

# 1. Total SUCCESS revenue

#a) Solution:

a_df = df.groupby("status")["amount"].sum()
a_df

status
FAILED      2999
PENDING     1049
SUCCESS    12742
Name: amount, dtype: int64

In [31]:
# b) Solution

a_df = df.groupby("status", as_index=False)["amount"].sum()
a_df

    status  amount
0   FAILED    2999
1  PENDING    1049
2  SUCCESS   12742

In [32]:
#c) solution
t_s_r = df[df["status"] == "SUCCESS"]["amount"].sum()
t_s_r

np.int64(12742)

In [33]:
# d) solution 

t_s_r_c = df.loc[df["status"] == "SUCCESS", "amount"].sum()
t_s_r_c

np.int64(12742)

In [34]:
# 2. Revenue by payment_method

p_df = df.groupby("payment_method", as_index = False)["amount"].sum()
p_df

  payment_method  amount
0           CARD    8096
1            COD    1898
2     NETBANKING    3249
3            UPI    3547

In [35]:
# 3. Count of transactions by status

c_df = df.groupby("status", as_index = False )["amount"].count()
c_df

    status  amount
0   FAILED       3
1  PENDING       2
2  SUCCESS      14

In [36]:
# 4. Average processing time by bank

a_df = df.groupby("bank", as_index = False)["processing_time_sec"].mean()
a_df

    bank  processing_time_sec
0   AXIS            14.333333
1   HDFC            18.500000
2  ICICI            20.600000
3  KOTAK            23.000000
4    SBI            22.000000

In [37]:
top3 = (
    df[df["status"] == "SUCCESS"]
    .groupby("city")["amount"]
    .sum()
    .sort_values(ascending=False)
    .head(3)
    .reset_index()
)
top3

        city  amount
0  Hyderabad    3248
1  Bangalore    3149
2      Delhi    2299

In [38]:
# 3.5 Pivot Table (Must for BA)

# 1. Create pivot: index=city, columns=status, values=amount, aggfunc=sum

pivot = df.pivot_table(index = "city", columns = "status" , values = "amount" , aggfunc = sum)
pivot

C:\Users\HP\AppData\Local\Temp\ipykernel_32252\1972060169.py:5: FutureWarning: The provided callable <built-in function sum> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  pivot = df.pivot_table(index = "city", columns = "status" , values = "amount" , aggfunc = sum)

status     FAILED  PENDING  SUCCESS
city
Bangalore  1299.0      NaN   3149.0
Chennai    1200.0      NaN    898.0
Delhi       500.0      NaN   2299.0
Hyderabad     NaN      NaN   3248.0
Mumbai        NaN    750.0   2249.0
Pune          NaN    299.0    899.0

In [39]:
# 3.6 String Operations

# 1. Convert city to uppercase

df["city_upper"] = df["city"].str.upper()
df["city_upper"]

0     BANGALORE
1       CHENNAI
2     HYDERABAD
3          PUNE
4        MUMBAI
5     BANGALORE
6         DELHI
7       CHENNAI
8     HYDERABAD
9     BANGALORE
10         PUNE
11        DELHI
12       MUMBAI
13        DELHI
14    BANGALORE
15      CHENNAI
16       MUMBAI
17    HYDERABAD
18    BANGALORE
Name: city_upper, dtype: object

In [40]:
# 2. Extract first character of bank name

df["bank_first"] = df["bank"].str[0]
df["bank_first"]

0     I
1     S
2     H
3     A
4     H
5     I
6     K
7     S
8     H
9     A
10    A
11    I
12    H
13    K
14    H
15    S
16    H
17    I
18    I
Name: bank_first, dtype: object

In [41]:
# 3. Check transactions where merchant_category contains 'Elect'

elect_df = df[df["merchant_category"].str.contains("Elect", na=False)]
elect_df

,txn_id,customer_id,txn_date,payment_method,status,amount,city,merchant_category,coupon_used,device,bank,processing_time_sec,city_upper,bank_first
0,T002,C002,01-01-2025,CARD,FAILED,1299,Bangalore,Electronics,NO,iOS,ICICI,35,BANGALORE,I
2,T004,C001,03-01-2025,COD,SUCCESS,999,Hyderabad,Electronics,NO,Android,HDFC,10,HYDERABAD,H
4,T006,C005,04-01-2025,CARD,SUCCESS,1999,Mumbai,Electronics,YES,iOS,HDFC,25,MUMBAI,H
7,T009,C003,06-01-2025,UPI,FAILED,1200,Chennai,Electronics,NO,iOS,SBI,40,CHENNAI,S
13,T015,C006,10-01-2025,NETBANKING,SUCCESS,1800,Delhi,Electronics,NO,Android,KOTAK,30,DELHI,K
14,T016,C011,10-01-2025,CARD,SUCCESS,2200,Bangalore,Electronics,YES,iOS,HDFC,27,BANGALORE,H

In [46]:
# 3.7 Datetime Operations

# 1. Extract year, month, day from txn_date

df["txn_date"] = pd.to_datetime(df["txn_date"], errors = "coerce")
df["txn_date"]

# df["year"] = df["txn_date"].dt.year
# df["year"]

0    2025-01-01
1    2025-02-01
2    2025-03-01
3    2025-03-01
4    2025-04-01
5    2025-04-01
6    2025-05-01
7    2025-06-01
8    2025-06-01
9    2025-07-01
10   2025-08-01
11   2025-08-01
12   2025-09-01
13   2025-10-01
14   2025-10-01
15   2025-11-01
16   2025-12-01
17   2025-12-01
18          NaT
Name: txn_date, dtype: datetime64[ns]

In [47]:
df["month"] = df["txn_date"].dt.month
df["month"]

0      1.0
1      2.0
2      3.0
3      3.0
4      4.0
5      4.0
6      5.0
7      6.0
8      6.0
9      7.0
10     8.0
11     8.0
12     9.0
13    10.0
14    10.0
15    11.0
16    12.0
17    12.0
18     NaN
Name: month, dtype: float64

In [48]:
df["day"] = df["txn_date"].dt.day
df["day"]

0     1.0
1     1.0
2     1.0
3     1.0
4     1.0
5     1.0
6     1.0
7     1.0
8     1.0
9     1.0
10    1.0
11    1.0
12    1.0
13    1.0
14    1.0
15    1.0
16    1.0
17    1.0
18    NaN
Name: day, dtype: float64

In [49]:
# 2. Filter last 7 days based on max date

max_date = df["txn_date"].max()

last_7_days = df[df["txn_date"] >= (max_date - pd.Timedelta(days=7))]
last_7_days

,txn_id,customer_id,txn_date,payment_method,status,amount,city,merchant_category,coupon_used,device,bank,processing_time_sec,city_upper,bank_first,month,day
16,T018,C005,2025-12-01,UPI,PENDING,750,Mumbai,Travel,YES,Android,HDFC,19,MUMBAI,H,12.0,1.0
17,T019,C007,2025-12-01,CARD,SUCCESS,1599,Hyderabad,Fashion,NO,iOS,ICICI,21,HYDERABAD,I,12.0,1.0

In [50]:
# 3. Group revenue by day (date-wise)

g_df = df.groupby("txn_date")["amount"].sum()
g_df

txn_date
2025-01-01    1299
2025-02-01     799
2025-03-01    1298
2025-04-01    2149
2025-05-01     499
2025-06-01    1850
2025-07-01     349
2025-08-01    1399
2025-09-01     250
2025-10-01    4000
2025-11-01      99
2025-12-01    2349
Name: amount, dtype: int64

In [51]:
# 3.8 Merge + Join Practice

customers = pd.DataFrame({
"customer_id": ["C001","C002","C003","C004","C005","C006"],
"customer_name": ["Aman","Sara","Neha","Raju","Faiz","Zoya"],
"age": [24, 27, 23, 29, 26, 25]
})
print("uploaded customers dataset")

uploaded customers dataset

In [62]:
# 1. Merge df with customers on customer_id

merged_df = pd.merge(df,customers,on= "customer_id")
merged_df

,txn_id,customer_id,txn_date,payment_method,status,amount,city,merchant_category,coupon_used,device,bank,processing_time_sec,city_upper,bank_first,month,day,customer_name,age
0,T002,C002,2025-01-01,CARD,FAILED,1299,Bangalore,Electronics,NO,iOS,ICICI,35,BANGALORE,I,1.0,1.0,Sara,27
1,T003,C003,2025-02-01,NETBANKING,SUCCESS,799,Chennai,Fashion,YES,Android,SBI,20,CHENNAI,S,2.0,1.0,Neha,23
2,T004,C001,2025-03-01,COD,SUCCESS,999,Hyderabad,Electronics,NO,Android,HDFC,10,HYDERABAD,H,3.0,1.0,Aman,24
3,T005,C004,2025-03-01,UPI,PENDING,299,Pune,Grocery,NO,Android,AXIS,18,PUNE,A,3.0,1.0,Raju,29
4,T006,C005,2025-04-01,CARD,SUCCESS,1999,Mumbai,Electronics,YES,iOS,HDFC,25,MUMBAI,H,4.0,1.0,Faiz,26
5,T007,C002,2025-04-01,UPI,SUCCESS,150,Bangalore,Grocery,NO,Android,ICICI,9,BANGALORE,I,4.0,1.0,Sara,27
6,T008,C006,2025-05-01,CARD,SUCCESS,499,Delhi,Fashion,YES,Android,KOTAK,16,DELHI,K,5.0,1.0,Zoya,25
7,T009,C003,2025-06-01,UPI,FAILED,1200,Chennai,Electronics,NO,iOS,SBI,40,CHENNAI,S,6.0,1.0,Neha,23
8,T012,C004,2025-08-01,COD,SUCCESS,899,Pune,Fashion,NO,Android,AXIS,14,PUNE,A,8.0,1.0,Raju,29
9,T015,C006,2025-10-01,NETBANKING,SUCCESS,1800,Delhi,Electronics,NO,Android,KOTAK,30,DELHI,K,10.0,1.0,Zoya,25
10,T018,C005,2025-12-01,UPI,PENDING,750,Mumbai,Travel,YES,Android,HDFC,19,MUMBAI,H,12.0,1.0,Faiz,26
11,T020,C002,NaT,UPI,SUCCESS,450,Bangalore,Travel,YES,Android,ICICI,10,BANGALORE,I,NaN,NaN,Sara,27

In [66]:
merged_df.columns

Index(['txn_id', 'customer_id', 'txn_date', 'payment_method', 'status',
       'amount', 'city', 'merchant_category', 'coupon_used', 'device', 'bank',
       'processing_time_sec', 'city_upper', 'bank_first', 'month', 'day',
       'customer_name', 'age'],
      dtype='object')

In [69]:
#2. Find rows where customer_name is missing after merge (unmatched customers)
    
merged_df = merged_df[merged_df["customer_name"].isna()]
merged_df

Empty DataFrame
Columns: [txn_id, customer_id, txn_date, payment_method, status, amount, city, merchant_category, coupon_used, device, bank, processing_time_sec, city_upper, bank_first, month, day, customer_name, age]
Index: []

In [73]:
merged_df.isna() # no missing values

Empty DataFrame
Columns: []
Index: []

In [71]:
# 3.9 Missing Data

# 1. Fill missing processing_time_sec with median -- No missing values

merged_df = merged_df[merged_df["processing_time_sec"].fillna(merged_df["processing_time_sec"].mean())]
merged_df

Empty DataFrame
Columns: []
Index: []

In [82]:
# 2. Drop rows where status is missing

# No missing values

In [85]:
# 1. Merge df with customers on customer_id

merged_df = pd.merge(df,customers,on= "customer_id")
merged_df

,txn_id,customer_id,txn_date,payment_method,status,amount,city,merchant_category,coupon_used,device,bank,processing_time_sec,city_upper,bank_first,month,day,customer_name,age
0,T002,C002,2025-01-01,CARD,FAILED,1299,Bangalore,Electronics,NO,iOS,ICICI,35,BANGALORE,I,1.0,1.0,Sara,27
1,T003,C003,2025-02-01,NETBANKING,SUCCESS,799,Chennai,Fashion,YES,Android,SBI,20,CHENNAI,S,2.0,1.0,Neha,23
2,T004,C001,2025-03-01,COD,SUCCESS,999,Hyderabad,Electronics,NO,Android,HDFC,10,HYDERABAD,H,3.0,1.0,Aman,24
3,T005,C004,2025-03-01,UPI,PENDING,299,Pune,Grocery,NO,Android,AXIS,18,PUNE,A,3.0,1.0,Raju,29
4,T006,C005,2025-04-01,CARD,SUCCESS,1999,Mumbai,Electronics,YES,iOS,HDFC,25,MUMBAI,H,4.0,1.0,Faiz,26
5,T007,C002,2025-04-01,UPI,SUCCESS,150,Bangalore,Grocery,NO,Android,ICICI,9,BANGALORE,I,4.0,1.0,Sara,27
6,T008,C006,2025-05-01,CARD,SUCCESS,499,Delhi,Fashion,YES,Android,KOTAK,16,DELHI,K,5.0,1.0,Zoya,25
7,T009,C003,2025-06-01,UPI,FAILED,1200,Chennai,Electronics,NO,iOS,SBI,40,CHENNAI,S,6.0,1.0,Neha,23
8,T012,C004,2025-08-01,COD,SUCCESS,899,Pune,Fashion,NO,Android,AXIS,14,PUNE,A,8.0,1.0,Raju,29
9,T015,C006,2025-10-01,NETBANKING,SUCCESS,1800,Delhi,Electronics,NO,Android,KOTAK,30,DELHI,K,10.0,1.0,Zoya,25
10,T018,C005,2025-12-01,UPI,PENDING,750,Mumbai,Travel,YES,Android,HDFC,19,MUMBAI,H,12.0,1.0,Faiz,26
11,T020,C002,NaT,UPI,SUCCESS,450,Bangalore,Travel,YES,Android,ICICI,10,BANGALORE,I,NaN,NaN,Sara,27

In [87]:
# 3.10 Window / Ranking in Pandas

# 1. For each city, rank transactions by amount descending


merged_df["amount_rank"] = (merged_df.groupby("city")["amount"].rank(method="dense",ascending= False))
merged_df

,txn_id,customer_id,txn_date,payment_method,status,amount,city,merchant_category,coupon_used,device,bank,processing_time_sec,city_upper,bank_first,month,day,customer_name,age,amount_rank
0,T002,C002,2025-01-01,CARD,FAILED,1299,Bangalore,Electronics,NO,iOS,ICICI,35,BANGALORE,I,1.0,1.0,Sara,27,1.0
1,T003,C003,2025-02-01,NETBANKING,SUCCESS,799,Chennai,Fashion,YES,Android,SBI,20,CHENNAI,S,2.0,1.0,Neha,23,2.0
2,T004,C001,2025-03-01,COD,SUCCESS,999,Hyderabad,Electronics,NO,Android,HDFC,10,HYDERABAD,H,3.0,1.0,Aman,24,1.0
3,T005,C004,2025-03-01,UPI,PENDING,299,Pune,Grocery,NO,Android,AXIS,18,PUNE,A,3.0,1.0,Raju,29,2.0
4,T006,C005,2025-04-01,CARD,SUCCESS,1999,Mumbai,Electronics,YES,iOS,HDFC,25,MUMBAI,H,4.0,1.0,Faiz,26,1.0
5,T007,C002,2025-04-01,UPI,SUCCESS,150,Bangalore,Grocery,NO,Android,ICICI,9,BANGALORE,I,4.0,1.0,Sara,27,3.0
6,T008,C006,2025-05-01,CARD,SUCCESS,499,Delhi,Fashion,YES,Android,KOTAK,16,DELHI,K,5.0,1.0,Zoya,25,2.0
7,T009,C003,2025-06-01,UPI,FAILED,1200,Chennai,Electronics,NO,iOS,SBI,40,CHENNAI,S,6.0,1.0,Neha,23,1.0
8,T012,C004,2025-08-01,COD,SUCCESS,899,Pune,Fashion,NO,Android,AXIS,14,PUNE,A,8.0,1.0,Raju,29,1.0
9,T015,C006,2025-10-01,NETBANKING,SUCCESS,1800,Delhi,Electronics,NO,Android,KOTAK,30,DELHI,K,10.0,1.0,Zoya,25,1.0
10,T018,C005,2025-12-01,UPI,PENDING,750,Mumbai,Travel,YES,Android,HDFC,19,MUMBAI,H,12.0,1.0,Faiz,26,2.0
11,T020,C002,NaT,UPI,SUCCESS,450,Bangalore,Travel,YES,Android,ICICI,10,BANGALORE,I,NaN,NaN,Sara,27,2.0

In [88]:
# 2. Get top 2 transactions per city (include ties using dense ranking)

merged_df["amount_rank"] = ( merged_df.groupby("city")["amount"].rank(method="dense",ascending=False))

top_2_per_city = merged_df[merged_df["amount_rank"] <=2]
top_2_per_city

,txn_id,customer_id,txn_date,payment_method,status,amount,city,merchant_category,coupon_used,device,bank,processing_time_sec,city_upper,bank_first,month,day,customer_name,age,amount_rank
0,T002,C002,2025-01-01,CARD,FAILED,1299,Bangalore,Electronics,NO,iOS,ICICI,35,BANGALORE,I,1.0,1.0,Sara,27,1.0
1,T003,C003,2025-02-01,NETBANKING,SUCCESS,799,Chennai,Fashion,YES,Android,SBI,20,CHENNAI,S,2.0,1.0,Neha,23,2.0
2,T004,C001,2025-03-01,COD,SUCCESS,999,Hyderabad,Electronics,NO,Android,HDFC,10,HYDERABAD,H,3.0,1.0,Aman,24,1.0
3,T005,C004,2025-03-01,UPI,PENDING,299,Pune,Grocery,NO,Android,AXIS,18,PUNE,A,3.0,1.0,Raju,29,2.0
4,T006,C005,2025-04-01,CARD,SUCCESS,1999,Mumbai,Electronics,YES,iOS,HDFC,25,MUMBAI,H,4.0,1.0,Faiz,26,1.0
6,T008,C006,2025-05-01,CARD,SUCCESS,499,Delhi,Fashion,YES,Android,KOTAK,16,DELHI,K,5.0,1.0,Zoya,25,2.0
7,T009,C003,2025-06-01,UPI,FAILED,1200,Chennai,Electronics,NO,iOS,SBI,40,CHENNAI,S,6.0,1.0,Neha,23,1.0
8,T012,C004,2025-08-01,COD,SUCCESS,899,Pune,Fashion,NO,Android,AXIS,14,PUNE,A,8.0,1.0,Raju,29,1.0
9,T015,C006,2025-10-01,NETBANKING,SUCCESS,1800,Delhi,Electronics,NO,Android,KOTAK,30,DELHI,K,10.0,1.0,Zoya,25,1.0
10,T018,C005,2025-12-01,UPI,PENDING,750,Mumbai,Travel,YES,Android,HDFC,19,MUMBAI,H,12.0,1.0,Faiz,26,2.0
11,T020,C002,NaT,UPI,SUCCESS,450,Bangalore,Travel,YES,Android,ICICI,10,BANGALORE,I,NaN,NaN,Sara,27,2.0

In [95]:
# 3.11 Rolling / Expanding

# 1. Rolling mean of amount per customer (window=3)


#Step 1: Sorting

# merged_df = merged_df.sort_values(["customer_id","txn_date"])

# #step 2: Rolling mean ( window = 3)

# merged_df["rolling_mean_3"] = ( merged_df.groupby("customer_id")["amount"].rolling(window=3).mean().reset_index(level=0,drop=True))
# merged_df

merged_df["rolling_mean_3"] = (
    merged_df
    .groupby("customer_id")["amount"]
    .rolling(window=3, min_periods=1)
    .mean()
    .reset_index(level=0, drop=True)
)
merged_df

,txn_id,customer_id,txn_date,payment_method,status,amount,city,merchant_category,coupon_used,device,bank,processing_time_sec,city_upper,bank_first,month,day,customer_name,age,amount_rank,rolling_mean_3
2,T004,C001,2025-03-01,COD,SUCCESS,999,Hyderabad,Electronics,NO,Android,HDFC,10,HYDERABAD,H,3.0,1.0,Aman,24,1.0,999.0
0,T002,C002,2025-01-01,CARD,FAILED,1299,Bangalore,Electronics,NO,iOS,ICICI,35,BANGALORE,I,1.0,1.0,Sara,27,1.0,1299.0
5,T007,C002,2025-04-01,UPI,SUCCESS,150,Bangalore,Grocery,NO,Android,ICICI,9,BANGALORE,I,4.0,1.0,Sara,27,3.0,724.5
11,T020,C002,NaT,UPI,SUCCESS,450,Bangalore,Travel,YES,Android,ICICI,10,BANGALORE,I,NaN,NaN,Sara,27,2.0,633.0
1,T003,C003,2025-02-01,NETBANKING,SUCCESS,799,Chennai,Fashion,YES,Android,SBI,20,CHENNAI,S,2.0,1.0,Neha,23,2.0,799.0
7,T009,C003,2025-06-01,UPI,FAILED,1200,Chennai,Electronics,NO,iOS,SBI,40,CHENNAI,S,6.0,1.0,Neha,23,1.0,999.5
3,T005,C004,2025-03-01,UPI,PENDING,299,Pune,Grocery,NO,Android,AXIS,18,PUNE,A,3.0,1.0,Raju,29,2.0,299.0
8,T012,C004,2025-08-01,COD,SUCCESS,899,Pune,Fashion,NO,Android,AXIS,14,PUNE,A,8.0,1.0,Raju,29,1.0,599.0
4,T006,C005,2025-04-01,CARD,SUCCESS,1999,Mumbai,Electronics,YES,iOS,HDFC,25,MUMBAI,H,4.0,1.0,Faiz,26,1.0,1999.0
10,T018,C005,2025-12-01,UPI,PENDING,750,Mumbai,Travel,YES,Android,HDFC,19,MUMBAI,H,12.0,1.0,Faiz,26,2.0,1374.5
6,T008,C006,2025-05-01,CARD,SUCCESS,499,Delhi,Fashion,YES,Android,KOTAK,16,DELHI,K,5.0,1.0,Zoya,25,2.0,499.0
9,T015,C006,2025-10-01,NETBANKING,SUCCESS,1800,Delhi,Electronics,NO,Android,KOTAK,30,DELHI,K,10.0,1.0,Zoya,25,1.0,1149.5

In [100]:
# 2. Cumulative sum of amount per customer

#Step 1: sort properly
merged_df = merged_df.sort_values(["customer_id","txn_date"])

#Step 2: Cumulative sum per customer

merged_df["cumulative_amount"] = ( merged_df.groupby("customer_id")["amount"].cumsum())
merged_df

,txn_id,customer_id,txn_date,payment_method,status,amount,city,merchant_category,coupon_used,device,...,processing_time_sec,city_upper,bank_first,month,day,customer_name,age,amount_rank,rolling_mean_3,cumulative_amount
2,T004,C001,2025-03-01,COD,SUCCESS,999,Hyderabad,Electronics,NO,Android,...,10,HYDERABAD,H,3.0,1.0,Aman,24,1.0,999.0,999
0,T002,C002,2025-01-01,CARD,FAILED,1299,Bangalore,Electronics,NO,iOS,...,35,BANGALORE,I,1.0,1.0,Sara,27,1.0,1299.0,1299
5,T007,C002,2025-04-01,UPI,SUCCESS,150,Bangalore,Grocery,NO,Android,...,9,BANGALORE,I,4.0,1.0,Sara,27,3.0,724.5,1449
11,T020,C002,NaT,UPI,SUCCESS,450,Bangalore,Travel,YES,Android,...,10,BANGALORE,I,NaN,NaN,Sara,27,2.0,633.0,1899
1,T003,C003,2025-02-01,NETBANKING,SUCCESS,799,Chennai,Fashion,YES,Android,...,20,CHENNAI,S,2.0,1.0,Neha,23,2.0,799.0,799
7,T009,C003,2025-06-01,UPI,FAILED,1200,Chennai,Electronics,NO,iOS,...,40,CHENNAI,S,6.0,1.0,Neha,23,1.0,999.5,1999
3,T005,C004,2025-03-01,UPI,PENDING,299,Pune,Grocery,NO,Android,...,18,PUNE,A,3.0,1.0,Raju,29,2.0,299.0,299
8,T012,C004,2025-08-01,COD,SUCCESS,899,Pune,Fashion,NO,Android,...,14,PUNE,A,8.0,1.0,Raju,29,1.0,599.0,1198
4,T006,C005,2025-04-01,CARD,SUCCESS,1999,Mumbai,Electronics,YES,iOS,...,25,MUMBAI,H,4.0,1.0,Faiz,26,1.0,1999.0,1999
10,T018,C005,2025-12-01,UPI,PENDING,750,Mumbai,Travel,YES,Android,...,19,MUMBAI,H,12.0,1.0,Faiz,26,2.0,1374.5,2749
6,T008,C006,2025-05-01,CARD,SUCCESS,499,Delhi,Fashion,YES,Android,...,16,DELHI,K,5.0,1.0,Zoya,25,2.0,499.0,499
9,T015,C006,2025-10-01,NETBANKING,SUCCESS,1800,Delhi,Electronics,NO,Android,...,30,DELHI,K,10.0,1.0,Zoya,25,1.0,1149.5,2299

In [ ]:
####END####